
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: always
  
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - 8086:8086
    restart: always
  
  telegraf:
    image: telegraf
    network_mode: "host"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock

